export let FLIGHTS = [
  {
    id: 1,
    name: "American Airlines",
    way: "roundtrip",
    totaltime: "1h 20m",
    departure: "7:35pm",
    arriving: "8:55pm",
    from: "LHR",
    to: "AMS",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/aairlines-logo.jpg",
    price: 100
  },
  {
    id: 2,
    name: "Air Canada",
    way: "roundtrip",
    totaltime: "2h 30m",
    departure: "1:10pm",
    arriving: "2:40pm",
    from: "LHR",
    to: "AMS",
    steps: "Nonstop",
    airplane: "Airbus A380",
    class: "Business",
    logo: "assets/img/flight/thumb/aircanada-logo.jpg",
    price: 320
  },
  {
    id: 3,
    name: "British Airways",
    way: "roundtrip",
    totaltime: "4h 00m",
    departure: "2:15pm",
    arriving: "6:15pm",
    from: "LHR",
    to: "NYC",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/britishairways-logo.jpg",
    price: 270.50
  },
  {
    id: 4,
    name: "Emirates",
    way: "roundtrip",
    totaltime: "0h 50m",
    departure: "7:35pm",
    arriving: "8:25pm",
    from: "JED",
    to: "CAI",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "First Class",
    logo: "assets/img/flight/thumb/emirates-logo.jpg",
    price: 400
  },
  {
    id: 5,
    name: "Iberia",
    way: "roundtrip",
    totaltime: "1h 10m",
    departure: "7:35pm",
    arriving: "8:45pm",
    from: "MAD",
    to: "LIS",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/iberia-logo.jpg",
    price: 130
  },
  {
    id: 6,
    name: "KLM",
    way: "roundtrip",
    totaltime: "0h 40m",
    departure: "7:35pm",
    arriving: "8:15pm",
    from: "AMS",
    to: "PAR",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Premium Economy",
    logo: "assets/img/flight/thumb/klm-logo.jpg",
    price: 190
  },
  {
    id: 7,
    name: "LATAM",
    way: "roundtrip",
    totaltime: "2h 15m",
    departure: "7:35pm",
    arriving: "9:50pm",
    from: "SAO",
    to: "SCL",
    steps: "1 Stop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/latam-logo.jpg",
    price: 190
  },
  {
    id: 8,
    name: "Lufthansa",
    way: "roundtrip",
    totaltime: "4h 15m",
    departure: "7:35pm",
    arriving: "11:50pm",
    from: "BER",
    to: "MOW",
    steps: "2 Stops",
    airplane: "Airbus A380",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/lufthansa-logo.jpg",
    price: 263
  }
]
