export let CRUISES = [
  {
    id: 1,
    name: "Cruise from Miami to Genoa",
    price_adult: 600,
    price_child: 300,
    time: "12 nights",
    date: "2019: Mar 29",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Miami; Funchal; Tenerife; Genoa",
    thumb: "assets/img/cruise/thumb/royal-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_1.jpg",
      "assets/img/cruise/thumb/cruise_6.jpg",
      "assets/img/cruise/thumb/cruise_7.jpg",
      "assets/img/cruise/thumb/cruise_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 2,
    name: "Cruise from Miami to Valencia",
    price_adult: 900,
    price_child: 450,
    time: "18 nights",
    date: "2018: Oct 10",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Miami; Ponta Delgada; Gibraltar; Alicante; Valencia",
    thumb: "assets/img/cruise/thumb/princess-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_2.jpg",
      "assets/img/cruise/thumb/cruise_6.jpg",
      "assets/img/cruise/thumb/cruise_7.jpg",
      "assets/img/cruise/thumb/cruise_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 3,
    name: "Cruise from Venice to Miami",
    price_adult: 1300,
    price_child: 650,
    time: "28 nights",
    date: "2019: Apr 9",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Venice; Ponta Delgada; Lisbon; Porto; Miami",
    thumb: "assets/img/cruise/thumb/ncl-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "São Paulo, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_3.jpg",
      "assets/img/cruise/thumb/cruise_4.jpg",
      "assets/img/cruise/thumb/cruise_6.jpg",
      "assets/img/cruise/thumb/cruise_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 4,
    name: "Cruise from Rio de Janeiro to Lisbon",
    price_adult: 1500,
    price_child: 750,
    time: "14 nights",
    date: "2019: Jan 13",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Rio de Janeiro; Natal; Kingston; Lisbon",
    thumb: "assets/img/cruise/thumb/msc-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_4.jpg",
      "assets/img/cruise/thumb/cruise_2.jpg",
      "assets/img/cruise/thumb/cruise_5.jpg",
      "assets/img/cruise/thumb/cruise_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 5,
    name: "Cruise from Santos to Havana",
    price_adult: 800,
    price_child: 400,
    time: "19 nights",
    date: "2018: Sep 26",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Santos; Salvador; Natal; Havana",
    thumb: "assets/img/cruise/thumb/disney-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_5.jpg",
      "assets/img/cruise/thumb/cruise_6.jpg",
      "assets/img/cruise/thumb/cruise_7.jpg",
      "assets/img/cruise/thumb/cruise_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 6,
    name: "Cruise from Kington to Ponta Delgada",
    price_adult: 1100,
    price_child: 550,
    time: "30 nights",
    date: "2019: Dez 22",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Kingston; Port of Prince; Ponta Delgada",
    thumb: "assets/img/cruise/thumb/costa-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_6.jpg",
      "assets/img/cruise/thumb/cruise_1.jpg",
      "assets/img/cruise/thumb/cruise_3.jpg",
      "assets/img/cruise/thumb/cruise_5.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 7,
    name: "Cruise from Havana to Bahamas",
    price_adult: 500,
    price_child: 250,
    time: "7 nights",
    date: "2018: Nov 21",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Havana; Port of Prince; Bahamas",
    thumb: "assets/img/cruise/thumb/celebrity-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_7.jpg",
      "assets/img/cruise/thumb/cruise_2.jpg",
      "assets/img/cruise/thumb/cruise_4.jpg",
      "assets/img/cruise/thumb/cruise_6.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 8,
    name: "Cruise from Porto to Macau",
    price_adult: 2800,
    price_child: 1400,
    time: "42 nights",
    date: "2019: May 1",
    free_cancellation: 1,
    electric_voucher: 1,
    ports: "Porto; Valencia; Port Elizabeth; Goa; Macau",
    thumb: "assets/img/cruise/thumb/carnival-logo.jpg",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [
      "assets/img/cruise/thumb/cruise_8.jpg",
      "assets/img/cruise/thumb/cruise_1.jpg",
      "assets/img/cruise/thumb/cruise_3.jpg",
      "assets/img/cruise/thumb/cruise_5.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  }
]
